
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1755, 773)
        MainWindow.setStyleSheet("")
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.top_left_f = QtWidgets.QFrame(self.main_widget)
        self.top_left_f.setGeometry(QtCore.QRect(9, 9, 471, 351))
        self.top_left_f.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_left_f.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_left_f.setObjectName("top_left_f")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.top_left_f)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_column_inner = QtWidgets.QFrame(self.top_left_f)
        self.left_column_inner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_column_inner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_column_inner.setObjectName("left_column_inner")
        self.frame_1 = QtWidgets.QFrame(self.left_column_inner)
        self.frame_1.setGeometry(QtCore.QRect(0, 240, 401, 56))
        self.frame_1.setObjectName("frame_1")
        self.left_column_top_box_button_container_4 = QtWidgets.QVBoxLayout(
            self.frame_1)
        self.left_column_top_box_button_container_4.setObjectName(
            "left_column_top_box_button_container_4")
        self.save_all_button_3 = QtWidgets.QPushButton(self.frame_1)
        self.save_all_button_3.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.save_all_button_3.setObjectName("save_all_button_3")
        self.left_column_top_box_button_container_4.addWidget(
            self.save_all_button_3)
        self.frame_2 = QtWidgets.QFrame(self.left_column_inner)
        self.frame_2.setGeometry(QtCore.QRect(90, 60, 341, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.time_converter_check_box = QtWidgets.QCheckBox(self.frame_2)
        self.time_converter_check_box.setGeometry(
            QtCore.QRect(0, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time_converter_check_box.setFont(font)
        self.time_converter_check_box.setObjectName("time_converter_check_box")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 281, 80))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.dropdown_menu = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.dropdown_menu.setContentsMargins(0, 0, 0, 0)
        self.dropdown_menu.setObjectName("dropdown_menu")
        self.index_dropdown = QtWidgets.QComboBox(self.layoutWidget_2)
        self.index_dropdown.setObjectName("index_dropdown")
        self.dropdown_menu.addWidget(self.index_dropdown)
        self.subject_dropdown = QtWidgets.QComboBox(self.layoutWidget_2)
        self.subject_dropdown.setObjectName("subject_dropdown")
        self.dropdown_menu.addWidget(self.subject_dropdown)
        self.device_dropdown = QtWidgets.QComboBox(self.layoutWidget_2)
        self.device_dropdown.setObjectName("device_dropdown")
        self.dropdown_menu.addWidget(self.device_dropdown)
        self.time_dates_container = QtWidgets.QSplitter(self.frame_2)
        self.time_dates_container.setGeometry(QtCore.QRect(0, 100, 294, 20))
        self.time_dates_container.setOrientation(QtCore.Qt.Horizontal)
        self.time_dates_container.setObjectName("time_dates_container")
        self.start_date = QtWidgets.QDateTimeEdit(self.time_dates_container)
        self.start_date.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.start_date.setObjectName("start_date")
        self.end_date = QtWidgets.QDateTimeEdit(self.time_dates_container)
        self.end_date.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.end_date.setObjectName("end_date")
        self.device_label = QtWidgets.QLabel(self.left_column_inner)
        self.device_label.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.device_label.setObjectName("device_label")
        self.subject_label = QtWidgets.QLabel(self.left_column_inner)
        self.subject_label.setGeometry(QtCore.QRect(10, 100, 52, 16))
        self.subject_label.setObjectName("subject_label")
        self.frame_3 = QtWidgets.QFrame(self.left_column_inner)
        self.frame_3.setGeometry(QtCore.QRect(1, 1, 391, 56))
        self.frame_3.setObjectName("frame_3")
        self.import_button = QtWidgets.QPushButton(self.frame_3)
        self.import_button.setGeometry(QtCore.QRect(9, 9, 381, 16))
        self.import_button.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.import_button.setObjectName("import_button")
        self.clear_button = QtWidgets.QPushButton(self.frame_3)
        self.clear_button.setGeometry(QtCore.QRect(9, 31, 381, 16))
        self.clear_button.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.clear_button.setObjectName("clear_button")
        self.index_label = QtWidgets.QLabel(self.left_column_inner)
        self.index_label.setGeometry(QtCore.QRect(10, 70, 39, 16))
        self.index_label.setObjectName("index_label")
        self.date_range_label = QtWidgets.QLabel(self.left_column_inner)
        self.date_range_label.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.date_range_label.setObjectName("date_range_label")
        self.verticalLayout.addWidget(self.left_column_inner)
        self.right_f = QtWidgets.QFrame(self.main_widget)
        self.right_f.setGeometry(QtCore.QRect(480, 10, 1251, 721))
        self.right_f.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_f.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_f.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_f.setObjectName("right_f")
        self.graph_area = QtWidgets.QScrollArea(self.right_f)
        self.graph_area.setGeometry(QtCore.QRect(10, 10, 1231, 701))
        self.graph_area.setWidgetResizable(True)
        self.graph_area.setObjectName("graph_area")
        self.graph_area_widget_contents = QtWidgets.QWidget()
        self.graph_area_widget_contents.setGeometry(
            QtCore.QRect(0, 0, 1229, 699))
        self.graph_area_widget_contents.setObjectName(
            "graph_area_widget_contents")
        self.graph_area.setWidget(self.graph_area_widget_contents)
        self.buttom_left_f = QtWidgets.QFrame(self.main_widget)
        self.buttom_left_f.setGeometry(QtCore.QRect(50, 360, 381, 371))
        self.buttom_left_f.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.buttom_left_f.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttom_left_f.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttom_left_f.setObjectName("buttom_left_f")
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1755, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setSeparatorsCollapsible(True)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_all_button_3.setText(_translate("MainWindow", "Select All"))
        self.time_converter_check_box.setText(
            _translate("MainWindow", "Standard Time"))
        self.device_label.setText(_translate("MainWindow", "Device"))
        self.subject_label.setText(_translate("MainWindow", "Subject  "))
        self.import_button.setText(_translate("MainWindow", "Import Data"))
        self.clear_button.setText(_translate("MainWindow", "Clear Data"))
        self.index_label.setText(_translate("MainWindow", "Index  "))
        self.date_range_label.setText(_translate("MainWindow", "Date Range"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
